title                    : "GitHub Pages - devinlfe.github.io"
name                     : " "
description              : "       "
url                      : "https://devinlife.github.io"
baseurl                  : <{{ site.url }}{{ site.baseurl }}/blog/start-blog/>

theme: jekyll-theme-minimal